plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  - scope:
      path: ''
    values:
      layout: 'main'

sass:
  style: compressed
  sass_dir: _sass

# SITE CONFIGURATION
title: Impact Labs
tagline: Inspiring and empowering young engineers to build a better world.
description: >
  Inspiring and empowering young engineers to build a better world. We host a summit, coalition, fellowship program, and much more!
baseurl: '/'
url: 'https://impactlabs.io/'
twitter:
  username: impactlabs_io

logo: 'https://impactlabs.io/assets/images/impact_labs.jpg'
