url: 'https://www.impactlabs.io/'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  - scope:
      path: ''
    values:
      layout: 'main'

sass:
  style: compressed
  sass_dir: _sass
